### ISSUE TITLE
(Fehler)Meldungen bei frischer Installation (xampp)

### ISSUE THREAD

**Issue by iceman-fx** [novinet-git/nv_betheme#3]
Nach Aktivierung des Addon erscheint oberhalb der Redaxo-Leiste folgende Ausgabe:

generateFiles(); // Include backend assets if (rex::isBackend() && $oBeTheme->addon->getConfig("active")) { rex_extension::register('PACKAGES_INCLUDED', 'nvBeTheme_add_backend_assets', rex_extension::LATE); } function nvBeTheme_add_backend_assets(rex_extension_point $ep) { $oBeTheme = new nvBeTheme; if ($oBeTheme->addon->getConfig("serverName") != rex::getServerName()) { $oBeTheme->addon->setConfig("serverName",rex::getServerName()); $oBeTheme->generateFiles(); } if (file_exists($oBeTheme->addon->getAssetsPath("backend.css"))) { rex_view::addCssFile($oBeTheme->addon->getAssetsUrl("backend.css")); } if (file_exists($oBeTheme->addon->getAssetsPath("backend.js"))) { rex_view::addJsFile($oBeTheme->addon->getAssetsUrl("backend.js")); } }

Des Weiteren passiert nichts, wenn man auf helle Navigation umschaltet.
Es bleibt blau/grün bei mir.

Rex 5.11 mit PHP 7.4.9
nv_betheme 1.1.3

**Comment by novinet-git** [comment]
Ist gefixt (sorry für die Dauer)
