### ISSUE TITLE
Button "Block hinzufügen" springt 1px

### ISSUE THREAD

**Issue by engel4u** [novinet-git/nv_betheme#4]
In der backend.css des Addons ist hinterlegt: 

.rex-slice-select > .dropdown > .btn-default:focus,
.rex-slice-select > .dropdown > .btn-default.focus,
.rex-slice-select > .dropdown > .btn-default:active,
.rex-slice-select > .dropdown > .btn-default.active,
.rex-slice-select > .dropdown > .btn-default:hover,
.rex-slice-select > .dropdown > .btn-default.hover,
.open > .rex-slice-select > .dropdown > .btn-default.dropdown-toggle,
.panel-info > .panel-heading,
.panel-add > .panel-heading,
.panel-edit > .panel-heading {
  background-color: {{color}};
  border-color: {{color}};
  border: 0;
  color: #fff;
}

Korrekt müsste dort für border 1px gesetzt werden, dann springt es beim onMouseOver nicht mehr. 

Ist nur eine Kleinigkeit...

**Comment by novinet-git** [comment]
Gefixt
