### ISSUE TITLE
PHP 8.1: Non-static method nvBeTheme::hex2rgba() cannot be called statically

### ISSUE THREAD

**Issue by godsdog** [novinet-git/nv_betheme#8]
Mit PHP 8.1 knallt es beim Backend Login:
`Error | Non-static method nvBeTheme::hex2rgba() cannot be called statically | redaxo/src/addons/nv_betheme/lib/fragments/login_background/core/login_background.php | 34`

**Comment by novinet-git** [comment]
Fix ist online
